"""create bots table

Revision ID: 8c7c4a566f78
Revises: a50c745e19b1
Create Date: 2026-07-09 12:10:23.897834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c7c4a566f78'
down_revision: Union[str, Sequence[str], None] = 'a50c745e19b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), server_default='1200', nullable=False),
    sa.Column('games_played', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('losses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('draws', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('draws >= 0', name='ck_bots_draws_non_negative'),
    sa.CheckConstraint('games_played >= 0', name='ck_bots_games_played_non_negative'),
    sa.CheckConstraint('losses >= 0', name='ck_bots_losses_non_negative'),
    sa.CheckConstraint('rating >= 0', name='ck_bots_rating_non_negative'),
    sa.CheckConstraint('wins + losses + draws = games_played', name='ck_bots_record_matches_games_played'),
    sa.CheckConstraint('wins >= 0', name='ck_bots_wins_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'name', name='uq_bots_game_id_name')
    )
    op.create_index('ix_bots_game_id_rating', 'bots', ['game_id', 'rating'], unique=False)
    op.create_index(op.f('ix_bots_id'), 'bots', ['id'], unique=False)
    op.alter_column("matches", "bot_one_id",
            existing_type=sa.VARCHAR(),
            type_=sa.Integer(),
            existing_nullable=False,
            postgresql_using="bot_one_id::integer",
        )
    op.alter_column("matches", "bot_two_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="bot_two_id::integer",
    )
    op.create_foreign_key('fk_matches_bot_one_id_bots', 'matches', 'bots', ['bot_one_id'], ['id'])
    op.create_foreign_key('fk_matches_bot_two_id_bots', 'matches', 'bots', ['bot_two_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_matches_bot_two_id_bots', 'matches', type_='foreignkey')
    op.drop_constraint('fk_matches_bot_one_id_bots', 'matches', type_='foreignkey')
    op.alter_column('matches', 'bot_two_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('matches', 'bot_one_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index('ix_bots_game_id_rating', table_name='bots')
    op.drop_index(op.f('ix_bots_id'), table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
