"""baseline schema

Revision ID: b4e57400891e
Revises: 
Create Date: 2026-07-09 16:31:11.749040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4e57400891e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('rating', sa.Integer(), server_default='1200', nullable=False),
    sa.Column('games_played', sa.Integer(), server_default='0', nullable=False),
    sa.Column('wins', sa.Integer(), server_default='0', nullable=False),
    sa.Column('losses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('draws', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('draws >= 0', name='ck_bots_draws_non_negative'),
    sa.CheckConstraint('games_played >= 0', name='ck_bots_games_played_non_negative'),
    sa.CheckConstraint('losses >= 0', name='ck_bots_losses_non_negative'),
    sa.CheckConstraint('rating >= 0', name='ck_bots_rating_non_negative'),
    sa.CheckConstraint('wins + losses + draws = games_played', name='ck_bots_record_matches_games_played'),
    sa.CheckConstraint('wins >= 0', name='ck_bots_wins_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'name', name='uq_bots_game_id_name')
    )
    op.create_index('ix_bots_game_id_rating', 'bots', ['game_id', 'rating'], unique=False)
    op.create_index(op.f('ix_bots_id'), 'bots', ['id'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('bot_one_id', sa.Integer(), nullable=False),
    sa.Column('bot_two_id', sa.Integer(), nullable=False),
    sa.Column('bot_one_rating_before', sa.Integer(), nullable=False),
    sa.Column('bot_two_rating_before', sa.Integer(), nullable=False),
    sa.Column('bot_one_rating_after', sa.Integer(), nullable=False),
    sa.Column('bot_two_rating_after', sa.Integer(), nullable=False),
    sa.Column('bot_one_rating_delta', sa.Integer(), nullable=False),
    sa.Column('bot_two_rating_delta', sa.Integer(), nullable=False),
    sa.Column('winner_bot_id', sa.Integer(), nullable=True),
    sa.Column('result_reason', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bot_one_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['bot_two_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['winner_bot_id'], ['bots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('moves',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('bot_id', sa.Integer(), nullable=False),
    sa.Column('move', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'move_number', name='uq_moves_match_id_move_number')
    )
    op.create_index(op.f('ix_moves_id'), 'moves', ['id'], unique=False)
    op.create_index(op.f('ix_moves_match_id'), 'moves', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moves_match_id'), table_name='moves')
    op.drop_index(op.f('ix_moves_id'), table_name='moves')
    op.drop_table('moves')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_bots_id'), table_name='bots')
    op.drop_index('ix_bots_game_id_rating', table_name='bots')
    op.drop_table('bots')
    # ### end Alembic commands ###
